import * as fs from "fs";
import * as path from "path";
import prettier from "prettier";
import {
  parseContractDeployment,
  readLatestDeploymentFiles,
} from "./deployment";

export type JsonAbi = unknown[];

export interface FrontendContractEntry {
  address: string;
  txHash: string;
  abi: JsonAbi;
}

export type FrontendContracts = Record<
  string,
  Record<string, FrontendContractEntry>
>;

const generatedContractComment = `/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";
`;

function extractJsonArray(output: string, start: number): string | undefined {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = start; index < output.length; index += 1) {
    const character = output[index];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (character === "\\") {
        escaped = true;
      } else if (character === '"') {
        inString = false;
      }
      continue;
    }

    if (character === '"') {
      inString = true;
    } else if (character === "[") {
      depth += 1;
    } else if (character === "]") {
      depth -= 1;
      if (depth === 0) {
        return output.slice(start, index + 1);
      }
    }
  }

  return undefined;
}

/**
 * Extracts the first valid JSON array from cargo-stylus/solc output.
 * The command may prepend compiler headers or append diagnostic text.
 */
export function parseAbiOutput(output: string): JsonAbi {
  const trimmedOutput = output.trim();
  let foundArrayStart = false;

  for (let index = 0; index < trimmedOutput.length; index += 1) {
    if (trimmedOutput[index] !== "[") continue;
    foundArrayStart = true;

    const candidate = extractJsonArray(trimmedOutput, index);
    if (!candidate) continue;

    try {
      const parsed: unknown = JSON.parse(candidate);
      if (Array.isArray(parsed)) return parsed;
    } catch {
      // A compiler header or diagnostic may contain '['. Keep searching.
    }
  }

  const firstJsonToken = trimmedOutput.search(/[[{]/);
  if (firstJsonToken >= 0 && trimmedOutput[firstJsonToken] === "{") {
    try {
      const parsed: unknown = JSON.parse(trimmedOutput.slice(firstJsonToken));
      if (!Array.isArray(parsed)) {
        throw new Error("Exported ABI must be a JSON array");
      }
    } catch (error) {
      if (
        error instanceof Error &&
        error.message === "Exported ABI must be a JSON array"
      ) {
        throw error;
      }
    }
  }

  if (!foundArrayStart && firstJsonToken < 0) {
    throw new Error("No JSON ABI found in cargo stylus output");
  }

  throw new Error("No valid JSON ABI array found in cargo stylus output");
}

export function writeCleanAbiFile(filePath: string, abi: JsonAbi): void {
  fs.writeFileSync(filePath, `${JSON.stringify(abi, null, 2)}\n`);
}

/**
 * Rebuilds the complete frontend declaration from deployment JSON + ABI files.
 * No address or transaction hash is read back from generated TypeScript.
 */
export function buildFrontendContracts(
  deploymentDir: string,
): FrontendContracts {
  const contracts: FrontendContracts = {};

  for (const deploymentFile of readLatestDeploymentFiles(deploymentDir)) {
    const deploymentDocument: unknown = JSON.parse(
      fs.readFileSync(deploymentFile.filePath, "utf8"),
    );

    if (
      typeof deploymentDocument !== "object" ||
      deploymentDocument === null ||
      Array.isArray(deploymentDocument)
    ) {
      throw new Error(
        `Deployment file ${deploymentFile.filePath} must contain a JSON object`,
      );
    }

    const chainContracts: Record<string, FrontendContractEntry> = {};
    for (const contractName of Object.keys(deploymentDocument).sort()) {
      const deployment = parseContractDeployment(
        deploymentDocument,
        contractName,
        deploymentFile.chainId,
      );
      const abiFilePath = path.resolve(
        deploymentDir,
        deployment.contractFolder,
      );

      if (!fs.existsSync(abiFilePath)) {
        throw new Error(
          `ABI file not found for ${contractName}: ${abiFilePath}`,
        );
      }

      chainContracts[contractName] = {
        address: deployment.address,
        txHash: deployment.txHash,
        abi: parseAbiOutput(fs.readFileSync(abiFilePath, "utf8")),
      };
    }

    contracts[deploymentFile.chainId] = chainContracts;
  }

  return contracts;
}

export async function generateTsAbi(
  deploymentDir: string,
  targetFile = path.resolve(
    __dirname,
    "../../../nextjs/contracts/deployedContracts.ts",
  ),
): Promise<void> {
  const deployedContracts = buildFrontendContracts(deploymentDir);
  const output = `${generatedContractComment}\nconst deployedContracts = ${JSON.stringify(
    deployedContracts,
    null,
    2,
  )} as const;\n\nexport default deployedContracts satisfies GenericContractsDeclaration;\n`;

  fs.mkdirSync(path.dirname(targetFile), { recursive: true });
  fs.writeFileSync(
    targetFile,
    await prettier.format(output, { parser: "typescript" }),
  );

  console.log(`📝 Regenerated frontend contracts at ${targetFile}`);
}
